---
# Modified version of the Travis CI config for the go-cmp project:
# https://github.com/google/go-cmp/blob/master/.travis.yml
sudo: false
language: go

# Build for MacOS and Linux.
os:
  - linux
  - osx

go: 1.10.x

script:
  - diff -u <(echo -n) <(gofmt -d .) # Catch any gofmt errors.
  - go build -o target/anon-$TRAVIS_OS_NAME # Catch any compile errors first.
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./... # Run the tests with coverage.

after_success:
  - bash <(curl -s https://codecov.io/bash)

# On a tag, we will publish the binary produced to the GitHub release.
deploy:
  provider: releases
  api_key:
    secure: "ezDOGZRKLTK4kbdm3cMJg/PbJw7Jx3XwtOwhppNEE5VR7mc3gAZVae3S6zydTnDICdpPJgCBzyMej2lmfLqCi6rfYIROlZw0IOKQm+V9E01/WTACrlVCmXuoeQArb1Q0KUUqr8buEaLgrau4fay/StVfgk2tAjrF02GWk8vNu4IglahUqR5oRqkBmnZrJD5i0Y9vZRuUa0y7YWVBQMknQHxrGTS3SzCfLAAuIggigQt8AfkfC3iWDllQnH4ElIKpc1qv8dfVu2qsqHxwlWrFHHGFVSDAgX1dvgtmR38NY9j+fXiJQ7gvFJzTcyemZuB1w7HYjr7Zk0+9SB5nJV5pZDTeGXLyO547HqAGDe/d4L1uEXBtpkImopz4qekKRCeG/jcUE6iTp9ZmZOGuLpEOOInDRj4pNLyY5RwPBxC7Cfk4J2Lo6/FOdpxv0O+4FsoKkr/+cU2Zm4uf2V8L0c6OwVNbglQe/lDJBLBrR1KUc5OYM07IVSuOJRyR77EUb6BXvK/qF2t7C8s/+n93KqRMcLNTezWy2QDb7LBJ9g1PNi6alF+CU//vtHROYPlxU+QFX/rH8HMD3aIx/bEdWdM06OnzbLsYwBw4tKb1huabJVjpvWANsPwhIk5xGOGhRqywY5aJS2lcHnFl5lvfXh1Szuk8ZMLix6pzm6Qip24QizU="
  file: target/anon-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    tags: true
